language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.7-dev

install:
addons:
  apt:
    packages:
    # for wxPython with Python2:
    - python-wxgtk2.8
    - python-wxtools
    - wx2.8-doc
    - wx2.8-examples
    - wx2.8-headers
    - wx2.8-i18n
    # for wxPython with Python3
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

# command to install dependencies
install: 
  - sudo apt-get update
  - if [[ $TRAVIS_PYTHON_VERSION == '3*' ]]; then wget "https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-14.04/wxPython-4.0.0a2.dev3038+953a2e5-cp35-cp35m-linux_x86_64.whl"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3*' ]]; then pip install wxPython-4.0.0a2.dev3038+953a2e5-cp35-cp35m-linux_x86_64.whl; fi
  - "pip install -r requirements.txt"

script: python -m pytest --cov=./ tests
